// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69NrSL2qC5ndojW5XG4XBpobMvxQhUPE',
    appId: '1:227376853942:web:52225ea64a64ba3b604717',
    messagingSenderId: '227376853942',
    projectId: 'snapdock-8c489',
    authDomain: 'snapdock-8c489.firebaseapp.com',
    storageBucket: 'snapdock-8c489.firebasestorage.app',
    measurementId: 'G-K0XSVLMTQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvS6gfwaF-Q3_WyT7REgnJx2L_bltz8U',
    appId: '1:227376853942:android:2bcc13c8c8b3cd1d604717',
    messagingSenderId: '227376853942',
    projectId: 'snapdock-8c489',
    storageBucket: 'snapdock-8c489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSj5TBa4uYMHHPXwmKHTpbBYZXLvksaOU',
    appId: '1:227376853942:ios:36de0df89c06b9b9604717',
    messagingSenderId: '227376853942',
    projectId: 'snapdock-8c489',
    storageBucket: 'snapdock-8c489.firebasestorage.app',
    iosBundleId: 'com.snapdock.videodownloader',
  );

}